hyperv_mgmt_msk: 24
hyperv_mgmt_gateway: "172.16.10.254"
hyperv_dns_servers: ["172.16.10.10","172.16.20.10"]
hyperv_set_switch_adapters: ["LAN1","LAN2"]
hyperv_iscsi_jumbo: true
hyperv_iscsi_msk: 24
hyperv_livemigration_msk: 24
hyperv_livemigration_vlanid: 13
hyperv_csv_msk: 24
hyperv_csv_vlanid: 14
hyperv_iscsi_1_target1_ip:
hyperv_
hyperv_
hyperv_
hyperv_
hyperv_
hyperv_
hyperv_
hyperv_
hyperv_